# Generated by Django 5.2.18.dev20260908164954 on 2026-09-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("score", models.FloatField()),
                ("positive", models.PositiveSmallIntegerField(default=0)),
                ("negative", models.PositiveSmallIntegerField(default=0)),
                ("neutral", models.PositiveSmallIntegerField(default=0)),
                ("count", models.PositiveSmallIntegerField(default=0)),
                ("engine", models.CharField(max_length=40)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
